openapi: 3.1.0
info:
  title: API Spec
paths:
  /categories:
    get:
      summary: 카테고리 목록 조회
      responses:
        "200":
          description: 카테고리 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 카테고리 ID
                    name:
                      type: string
                      description: 카테고리 이름
              example:
                - id: 0
                  name: 자유 게시판
                - id: 1
                  name: 문의사항
  /categories/{id}/posts:
    get:
      summary: 카테고리 게시글 조회
      parameters:
        - name: id
          in: path
          required: true
          description: 조회할 카테고리의 ID
          schema:
            type: integer
          example: 0
        - name: offset
          in: query
          required: true
          description: 게시글 목록의 시작 위치
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: true
          description: 게시글 목록의 최대 개수
          schema:
            type: integer
          example: 20
      responses:
        "200":
          description: 카테고리 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  postCount:
                    type: integer
                    description: 카테고리에 속한 게시글 수
                  posts:
                    type: array
                    description: 카테고리에 속한 게시글 목록
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: 게시글 ID
                        author:
                          type: object
                          description: 게시글 작성자 정보
                          properties:
                            name:
                              type: string
                              description: 작성자 이름
                            hash:
                              type: string
                              description: 작성자 해시
                        category:
                          type: object
                          description: 게시글이 속한 카테고리 정보
                          properties:
                            id:
                              type: integer
                              description: 카테고리 ID
                            name:
                              type: string
                              description: 카테고리 이름
                        title:
                          type: string
                          description: 게시글 제목
                        createdAt:
                          type: string
                          description: 게시글 작성 시간
              example:
                postCount: 3
                posts:
                  - id: 0
                    author:
                      name: 익명
                      hash: deb31d415ad39db3
                    category:
                      id: 0
                      name: 자유 게시판
                    title: 게시물 1
                    createdAt: 2025-08-13T14:23:40.926Z
                  - id: 1
                    author:
                      name: 익명
                      hash: 7e6daed71421bf35
                    category:
                      id: 0
                      name: 자유 게시판
                    title: 게시물 2
                    createdAt: 2025-08-13T14:23:40.926Z
                  - id: 2
                    author:
                      name: 익명
                      hash: f91c5c2dd839cd5e
                    category:
                      id: 0
                      name: 자유 게시판
                    title: 게시물 3
                    createdAt: 2025-08-13T14:23:40.926Z
        "404":
          description: 카테고리를 찾을 수 없음
  /posts:
    post:
      summary: 게시글 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                  description: 게시글 작성자 이름
                password:
                  type: string
                  description: 게시글 비밀번호
                categoryId:
                  type: integer
                  description: 게시글이 속할 카테고리 ID
                title:
                  type: string
                  description: 게시글 제목
                content:
                  type: string
                  description: 게시글 내용
            example:
              author: "익명"
              password: "password123"
              categoryId: 0
              title: "게시글 1"
              content: "안녕하세요"
      responses:
        "201":
          description: 게시글이 성공적으로 생성됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 생성된 게시글의 ID
              example:
                id: 0
  /posts/{id}:
    get:
      summary: 게시글 조회
      parameters:
        - name: id
          in: path
          required: true
          description: 조회할 게시글의 ID
          schema:
            type: integer
          example: 0
      responses:
        "200":
          description: 게시글 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 게시글 ID
                  author:
                    type: object
                    description: 게시글 작성자 정보
                    properties:
                      name:
                        type: string
                        description: 작성자 이름
                      hash:
                        type: string
                        description: 작성자 해시
                  category:
                    type: object
                    description: 게시글이 속한 카테고리 정보
                    properties:
                      id:
                        type: integer
                        description: 카테고리 ID
                      name:
                        type: string
                        description: 카테고리 이름
                  title:
                    type: string
                    description: 게시글 제목
                  content:
                    type: string
                    description: 게시글 내용
                  createdAt:
                    type: string
                    description: 게시글 작성 시간
              example:
                id: 0
                author:
                  name: 익명
                  hash: deb31d415ad39db3
                category:
                  id: 0
                  name: 자유 게시판
                title: 게시물 1
                content: 안녕하세요
                createdAt: 2025-08-13T14:23:40.926Z
        "404":
          description: 게시글을 찾을 수 없음
    delete:
      summary: 게시글 삭제
      parameters:
        - name: id
          in: path
          required: true
          description: 삭제할 게시글의 ID
          schema:
            type: integer
          example: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 게시글 비밀번호
            example:
              password: "password123"
      responses:
        "204":
          description: 게시글이 성공적으로 삭제됨
        "403":
          description: 비밀번호가 일치하지 않음
        "404":
          description: 게시글을 찾을 수 없음
  /posts/{id}/comments:
    get:
      summary: 댓글 조회
      parameters:
        - name: id
          in: path
          required: true
          description: 댓글을 조회할 게시글의 ID
          schema:
            type: integer
          example: 0
        - name: offset
          in: query
          required: true
          description: 댓글 목록의 시작 위치
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: true
          description: 댓글 목록의 최대 개수
          schema:
            type: integer
          example: 20
      responses:
        "200":
          description: 댓글 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 댓글 ID
                    author:
                      type: object
                      description: 댓글 작성자 정보
                      properties:
                        name:
                          type: string
                          description: 작성자 이름
                        hash:
                          type: string
                          description: 작성자 해시
                    content:
                      type: string
                      description: 댓글 내용
                    createdAt:
                      type: string
                      description: 댓글 작성 시간
              example:
                - id: 0
                  author:
                    name: 익명
                    hash: 7e6daed71421bf35
                  content: 안녕하세요
                  createdAt: 2025-08-13T14:23:40.926Z
                - id: 1
                  author:
                    name: 익명
                    hash: f91c5c2dd839cd5e
                  content: 안녕하세요
                  createdAt: 2025-08-13T14:23:40.926Z
        "404":
          description: 게시글을 찾을 수 없음
    post:
      summary: 댓글 생성
      parameters:
        - name: id
          in: path
          required: true
          description: 댓글을 작성할 게시글의 ID
          schema:
            type: integer
          example: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                  description: 댓글 작성자 이름
                password:
                  type: string
                  description: 댓글 비밀번호
                content:
                  type: string
                  description: 댓글 내용
            example:
              author: "익명"
              password: "password123"
              content: "안녕하세요"
      responses:
        "201":
          description: 댓글이 성공적으로 작성됨
        "404":
          description: 게시글을 찾을 수 없음
  /comments/{id}:
    delete:
      summary: 댓글 삭제
      parameters:
        - name: id
          in: path
          required: true
          description: 삭제할 댓글의 ID
          schema:
            type: integer
          example: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 댓글 비밀번호
            example:
              password: "password123"
      responses:
        "204":
          description: 댓글이 성공적으로 삭제됨
        "403":
          description: 비밀번호가 일치하지 않음
        "404":
          description: 댓글을 찾을 수 없음
